### ISSUE TITLE
Enormous amount of logs appears in console on attempt to use element.clickIfPresent(3);

### ISSUE THREAD

**Issue by Litsvin** [qaprosoft/carina#459] opened 2018-09-27 11:04 UTC
carina 5.3.0.121

following block appears few time:
2018-09-26 17:00:51 DriverListener [main-1] [ERROR] [SM-G950F] org.openqa.selenium.WebDriverException: Method has not yet been implemented (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'user', ip: 'something', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.5', java.version: '1.8.0_171'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {....}
Session ID: f8f4cf70-5af6-4b62-98f5-de30dde0d683

**Comment by vdelendik** [comment] 2018-10-05 00:50
I hope fix is delivered in scope of changes for 5.3.0.559-SNAPSHOT build

**Comment by Litsvin** [comment] 2018-11-06 11:32
huge stack trace appears again.
appium 1.9.1+
carina 5.3.2.126

see following few times:
2018-11-06 14:29:28 DriverListener [main-1] [ERROR] [SM-G960F] java.net.SocketException: Connection reset
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'user-NW1465', ip: 'fe80:0:0:0:c38:a019:a754:2022%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.5', java.version: '1.8.0_171'
Driver info: driver.version: AndroidDriver
2018-11-06 14:29:30 Device [main-1] [INFO] [SM-G960F] UI dump generation...
2018-11-06 14:29:30 Device [main-1] [INFO] [SM-G960F] XML file path: /Users/user/projects/hh/./reports/qa/1541503682364/872e382b-5d59-4a64-9e14-db9170acd2d0/1541503768904.uix
2018-11-06 14:29:30 DriverListener [main-1] [ERROR] [SM-G960F] io.appium.uiautomator2.common.exceptions.StaleElementReferenceException: The element 'fc33cab8-332d-4bf9-a8db-68f9c0326635' does not exist in DOM anymore
	at io.appium.uiautomator2.model.KnownElements.getElementFromCache(KnownElements.java:85)
	at io.appium.uiautomator2.handler.GetElementAttribute.safeHandle(GetElementAttribute.java:24)
	at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:37)
	at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:250)
	at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:241)
	at io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:44)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:466)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:764)
 (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds

**Comment by vdelendik** [comment] 2019-01-04 19:34
connection reset means server is overloaded. It is recommended to decrease number of threads for execution.
As about "org.openqa.selenium.WebDriverException: Method has not yet been implemented" root cause was identified and fixed in #574

**Closed by vdelendik** 2019-01-04 19:34 UTC
