### ISSUE TITLE
L10N class ignores files named with 4 letters.

### ISSUE THREAD

**Issue by dprymudrau** [qaprosoft/carina#1110] opened 2020-09-11 11:48 UTC
Create resource bundle with default file name with 4 letters for l10n feature. init() method ignore files if default name of file has 4 letters or if it has underscore and then 4 letters(ex. demo.properties, carina_demo.properties).
Problem part of init() method:
```
if (fileName.lastIndexOf('_') == fileName.length() - 3
       || fileName.lastIndexOf('_') == fileName.length() - 5) {
     LOGGER.debug(String
             .format("'%s' resource IGNORED as it looks like localized resource!",
                                    fileName));
     continue;
}
```

**Comment by vdelendik** [comment] 2020-10-20 12:54
closing as not a bug

**Closed by vdelendik** 2020-10-20 12:54 UTC
Labels: bug
