### ISSUE TITLE
Device name is missing from logs...

### ISSUE THREAD

**Issue by Litsvin** [qaprosoft/carina#382] opened 2018-07-12 15:25 UTC
it's pretty often that in case of skipped test i have logges like:

[2018-07-12 01:46:47] [LoginService.java] [24] [INFO] Users are already registered. Count is: 2
[2018-07-12 01:46:47] [BaseTest.java] [24] [INFO] Connected to  for thread: 24
[2018-07-12 01:46:47] [ApiSingleton.java] [24] [INFO] api > createuser(usersresponse, user) > user: User [username=
[2018-07-12 01:46:47] [TestNamingUtil.java] [24] [WARN] Unable to find registered test name for threadId: 24. stack is null!
[2018-07-12 01:46:47] [TestNamingUtil.java] [24] [WARN] Unable to find registered test name for threadId: 24. stack is null!
[2018-07-12 01:46:47] [TestNamingUtil.java] [24] [WARN] Unable to find registered test name for threadId: 24. stack is null!
[2018-07-12 01:46:47] [Messager.java] [24] [INFO] 
======================================================================================================================================
INFO: TEST [feed tests (5 | test) - test] STARTED at [13:46:47 2018-07-12]
[2018-07-12 01:46:47] [Messager.java] [24] [INFO] 
INFO: TEST  [feed tests (5 | test) - test] SKIPPED at [13:46:47 2018-07-12] - null

com.project.retrofit.projectApiSingleton.createUser(projectApiSingleton.java:102)
com.project.activityfeed.ActivityFeedTest.logInTest(ActivityFeedTest.java:65)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
org.testng.TestRunner.privateRun(TestRunner.java:767)
org.testng.TestRunner.run(TestRunner.java:617)
org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:382)
org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

in case i have a device pool of about 20 devices, and all logs are mixed in one heap on jenkins - it's very complicated to determine device and track logs for one particular test

**Comment by vdelendik** [comment] 2019-01-09 18:37
dupe of #436

**Closed by vdelendik** 2019-01-09 18:37 UTC
