### ISSUE TITLE
add opportunity to build one test from fork synchronically on the several mobile devices

### ISSUE THREAD

**Issue by dariayakubovich** [qaprosoft/carina#187] opened 2017-11-29 12:17 UTC

**Comment by vdelendik** [comment] 2018-03-13 23:04
extended release cron version for mobile. good idea

**Comment by vdelendik** [comment] 2021-03-09 23:33
closing as won't fix because we have fancy regression matrix feature on pipeline-ce level to achieve such behaviour

**Closed by vdelendik** 2021-03-09 23:33 UTC
Labels: enhancement, wontfix
