### ISSUE TITLE
Carina + hub node configuration with IE instances

### ISSUE THREAD

**Issue by prasadjshimpi** [qaprosoft/carina#1069] opened 2020-07-01 07:34 UTC
Our set-up is automation using Carina and our own hub/node for distributed test execution.
Runner file has two tags from feature file AND is designed based on this reference (https://cucumber.io/docs/guides/parallel-execution/)

@io.cucumber.testng.CucumberOptions(features = "classpath:features/T3",
glue = "somepackage.steps", 
tags= "@Tag1 or @Tag2",
monochrome=true, dryRun = false,
plugin={"pretty",
        "html:target/cucumber-core-test-report",
        "pretty:target/cucumber-core-test-report.txt",
        "json:target/cucumber-core-test-report.json",
        "junit:target/cucumber-core-test-report.xml",
        "rerun:target/failed.txt"}
)
public class TestNGRunner extends AbstractTestNGCucumberTests {
 
 @Override
    @DataProvider(parallel = true)
    public Object[][] scenarios() {
        return super.scenarios();
    }
}
 
TestNG XML suite has reference to this runner and starting test in parallel on two IE instances.
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite verbose="1" name="T3" parallel="classes" thread-count="2" annotations="JDK">
    <parameter name="suiteOwner" value="qa"/>
    <parameter name="zafira_project" value="T3"/>

    <parameter name="jenkinsJobName" value="t3-Web-Test"/>
    <parameter name="jenkinsJobType" value="web"/>
    <parameter name="jenkinsEnvironments" value="QA1,PERF"/>

    <test verbose="1" name="Test Application ">
        <classes>
            <class name="com.test.runners.TestNGRunner"></class>
        </classes>
    </test>
</suite>

When we run test, on node we see two IE instances start and feature scenarios execute.
But
1. When there is some failure (such as element not found etc), carina is not able to close the browser window and We see following in log
2020-06-30 17:04:55 IDriverPool [TestNG-PoolService-1-14] [ERROR] Error discovered during driver quit: null
java.lang.NullPointerException
 at com.qaprosoft.carina.core.foundation.webdriver.IDriverPool.quitDriver(IDriverPool.java:384)
 at com.qaprosoft.carina.core.foundation.webdriver.IDriverPool.quitDriver(IDriverPool.java:278)
 at com.qaprosoft.carina.core.foundation.webdriver.IDriverPool.quitDriver(IDriverPool.java:245)

2. A folder for the Cucumber report gets created but file emailable-report.html is not getting created.
3. When I run tests in debug mode I don’t see the last line for CarinaListner$ShutdownHook getting called.
Is this something which you can review. The reason We are exploring this option because using this we don’t have to duplicate runner files into the TestNG XML file.
Or if you have any other suggestions to distribute feature file execution on different nodes, pls let me know.

**Comment by vdelendik** [comment] 2021-03-09 23:42
closed as can't reproduce

**Closed by vdelendik** 2021-03-09 23:42 UTC
Labels: enhancement
