### ISSUE TITLE
Create a plugin for Intellij, Eclipse

### ISSUE THREAD

**Issue by brutskov** [qaprosoft/carina#347] opened 2018-06-13 12:59 UTC
It will improve a possibility to help user with ide internal features like set breakpoint with error throwing etc.

**Comment by vdelendik** [comment] 2019-12-07 13:44
I'm thinking about online editor as part of infrastructure. 
https://github.com/qaprosoft/carina/issues/564
or even embedded eclipse as part of qps-infra

**Comment by vdelendik** [comment] 2021-03-09 23:35
closing as dupe of https://github.com/zebrunner/zebrunner/issues/84

**Closed by vdelendik** 2021-03-09 23:35 UTC
