### ISSUE TITLE
ITestCases.setCases doesn't publish all test results to TestRail

### ISSUE THREAD

**Issue by mohamadli** [qaprosoft/carina#707] opened 2019-05-02 18:36 UTC
Carina version: 6.0.16
Zafira: Cloud
QPS-pipeline: master

I use data providers + ITestCases.setCases instead of @ TestRailCases annotation to publish results to TestRail. Despite tests passed, some corresponding tests in TestRail are still marked Untested.

Important: while some results are published using setCases, another are still Untested (= sporadically reproducible problem).

Nothing suspicious in Carina logs.

setCases generates non-valid value for Zafira-TestRail integration?

Integration always works for TestRailCases annotated tests. The problem is only reproducible for ITestCases.setCases.

**Comment by kolyakrasnik** [comment] 2019-05-08 17:07
The root cause is determined. The issue is in zafira listener. Will be fixed soon. Will let you know, when the issue is fixed.

**Comment by vdelendik** [comment] 2019-05-09 09:21
https://github.com/qaprosoft/zafira/pull/1540
https://github.com/qaprosoft/carina/pull/714

fixes should be available in 6.1.20+ carina and 4.0.52+ zafira and 4.0.56+ zafira-client

**Closed by vdelendik** 2019-05-09 09:21 UTC
Labels: bug
