### ISSUE TITLE
Cucumber features should be allowed to run in parallel

### ISSUE THREAD

**Issue by prasadjshimpi** [qaprosoft/carina#929] opened 2020-03-07 08:20 UTC
I have tried to make changes in testng suite XML file as parallel=tests
But not working.

Hence there's suggestion that carina framework should support something as multiple and Independent feature file should be run in parallel which will reduce the execution time.

We have designed our all feature files independent.

if there are multiple feature files like (abc.feature and pqr.feature) and if I want to run them in parallel how to do that with testng.xml?

**Comment by vdelendik** [comment] 2021-03-09 23:39
closing as not a bug.

**Closed by vdelendik** 2021-03-09 23:39 UTC
Labels: enhancement, invalid
