### ISSUE TITLE
Improve test registration flow

### ISSUE THREAD

**Issue by brutskov** [qaprosoft/carina#951] opened 2020-03-25 19:11 UTC
**Describe the solution you'd like**
It is possible to register ZafiraListener on Carina framework side: create META-INF/services/org.testng.ITestNGListener file in core resources folder and provide information about ZafiraListener relative location into the file.
It allows to:
1. Implicity listener registration
2. Run fractional items like class or tests with Zafira registration
3. Faster launching of customer projects with Carina framework

![image](https://user-images.githubusercontent.com/20353034/77576156-b74c0480-6ee5-11ea-9a05-95339b11a475.png)
`com.qaprosoft.......ZafiraListener` inside

**Comment by vdelendik** [comment] 2020-03-25 19:18
:+1:

**Comment by vdelendik** [comment] 2020-04-18 10:16
consider comment from #851 which was closed as dupe of the current ticket:
![image](https://user-images.githubusercontent.com/4551455/79635002-d4879200-8176-11ea-8ce6-2ba2b40d0340.png)

**Comment by vdelendik** [comment] 2020-04-20 20:23
improvement merged to master. testing is in progress

**Comment by vdelendik** [comment] 2020-04-21 09:04
changes are available in 6.4.34+.
it is fully compatible with previous versions of pom.xml and suites xml files with extra ZafiraLsitener

**Closed by vdelendik** 2020-04-21 09:04 UTC
Labels: enhancement
