### ISSUE TITLE
Chrome download is getting failed after release 6.4.43 onwards.

### ISSUE THREAD

**Issue by prasadjshimpi** [qaprosoft/carina#1201] opened 2020-11-17 15:12 UTC
Chrome download is getting failed after release 6.4.43 onwards.
Attaching logs and screenshot for reference

[6.4.41_Working.txt](https://github.com/qaprosoft/carina/files/5554357/6.4.41_Working.txt)

[6.4.43.txt](https://github.com/qaprosoft/carina/files/5554345/6.4.43.txt)

![image](https://user-images.githubusercontent.com/31615407/99407640-55795880-2915-11eb-9fb9-1881a99aa787.png)

**Comment by vdelendik** [comment] 2021-01-12 20:15
closing as can't reproduce.
could you please test using 6.5.46 and 7.0.0-SNAPSHOT core versions?

**Closed by vdelendik** 2021-01-12 20:15 UTC
Labels: bug
