### ISSUE TITLE
Getting null pointer exception on multiple browser launch

### ISSUE THREAD

**Issue by prasadjshimpi** [qaprosoft/carina#1141] opened 2020-10-15 10:11 UTC
Code is able to open the two browsers as per code but while shutdown hook we get Null pointer exception.

Code :
public class diffAppLaunchTest extends AbstractTest {
    @Test
    public void diffAppLaunch(){
        System.out.println("Current Browser Value : " + R.CONFIG.get("browser"));
        TestPage testPage = new TestPage(getDriver("my-chrome-driver"));
        testPage.openURL(R.CONFIG.get("url1.base"));
        R.CONFIG.put("browser","ie",true);
        TestPage testPage1 = new TestPage(getDriver("my-ie-driver"));
        testPage1.openURL(R.CONFIG.get("url2.base"));
        System.out.println("Latest Browser Value : " + R.CONFIG.get("browser"));
    }
}

**Logs/Links**
Please refer to the attached screenshot

Carina Version : 6.4.41 and 6.4.43
![NPE_Error](https://user-images.githubusercontent.com/31615407/96109686-87edfb00-0efc-11eb-9b6d-b06b1e748876.png)

**Web (please complete the following information):**
 - Browser chrome (86), IE(3.150.1)

**Comment by vdelendik** [comment] 2020-10-29 11:03
closing as can't reproduce. based on the logs above something wrong with TestNG as it's result object is null. Feel free to reopen again especially if you have more details

**Closed by vdelendik** 2020-10-29 11:03 UTC
Labels: bug
